name: Release
description: |
  Release a new package version.
  This workflow is manually triggered via workflow_dispatch.
  Set repository variable IS_TEST_PKG=true to run in test mode.

on:
  workflow_dispatch:
    inputs:
      debian-branch:
        description: The debian branch to release. For example branch "qcom/debian/trixie"
        type: string
        required: true

permissions:
  contents: write
  packages: read
  checks: write

jobs:
  Release:
    uses: qualcomm-linux/qli-ci/.github/workflows/pkg-release-reusable-workflow.yml@main
    with:
      qli-ci-ref: main
      debian-branch: ${{ github.event.inputs.debian-branch }}
      test-run: ${{ vars.IS_TEST_PKG == 'true' }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE }}
      debusine-target-workspace: ${{ vars.DEBUSINE_TARGET_WORKSPACE || (vars.IS_TEST_PKG == 'true' && 'qli-staging' || 'prod') }}
    secrets:
      PAT: ${{ secrets.DEB_PKG_BOT_CI_TOKEN }}
      DEBUSINE_USER: ${{ secrets.DEBUSINE_USER }}
      DEBUSINE_TOKEN: ${{ secrets.DEBUSINE_TOKEN }}
      DEBUSINE_RELEASE_TOKEN: ${{ secrets.DEBUSINE_RELEASE_TOKEN }}
      QSC_API_KEY: ${{ secrets.DEB_PKG_BOT_CI_QSC_TOKEN }}
